apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: phishing-detector
  labels:
    app: phishing-detector
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: phishing-detector.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: phishing-detector
            port:
              number: 8000
